
# tap repositories and their packages

tap homebrew/core
brew aws-nuke
brew aws-shell
brew aws-vault
brew awscli
brew awscli-local
brew awslogs
brew awsume
brew awsweeper
brew bat
brew bat-extras
brew bore-cli
brew catimg
brew cheat
brew checkov
brew d2
brew diff-so-fancy
brew difftastic
brew direnv
brew dive
brew dnstop
brew eza
brew fastgron
brew fd
brew forgit
brew fzf
brew gh
brew git-delta
brew git-interactive-rebase-tool
brew glab
brew glow
brew go
brew gron
brew grype
brew hcledit
brew hstr
brew hub
brew infracost
brew inxi
brew k9s
brew kind
brew krew
brew kubecolor
brew kubectx
brew kubernetes-cli
brew lazydocker
brew lazygit
brew lnav
brew localstack
brew minikube
brew mods
brew mongosh
brew neofetch
brew nerdctl
brew nnn
brew peco
brew pipx
brew plantuml
brew pre-commit
brew ranger
brew ripgrep
brew starship
brew stern
brew tailspin
brew tenv
brew terraform-docs
brew terraform-graph-beautifier
brew terraform-local
brew terraform-provider-libvirt
brew terraform-rover
brew terraform_landscape
brew terrahelp
brew terrascan
brew tfk8s
brew tflint
brew tfmigrate
brew tfschema
brew tfsec
brew tfupdate
brew the_silver_searcher
brew tlrc
brew trippy
brew trivy
brew trzsz-go
brew ttyd
brew vale
brew zoxide
brew zsh-completions

tap aquaproj/aqua
brew aquaproj/aqua/aqua

tap aurc/loggo
brew aurc/loggo/loggo

tap charmbracelet/tap
brew charmbracelet/tap/soft-serve

tap fluxcd/tap
brew fluxcd/tap/flux

tap future-architect/tap
brew future-architect/tap/tftarget

tap hashicorp/tap
brew hashicorp/tap/vagrant

tap jckuester/tap
brew jckuester/tap/awsls

tap jmattaa/laser
brew jmattaa/laser/laser

tap one2nc/cloudlens
brew one2nc/cloudlens/cloudlens

tap rcmdnk/file
brew rcmdnk/file/brew-file

tap weaveworks/tap
brew weaveworks/tap/gitops

tap wez/wezterm-linuxbrew
brew wez/wezterm-linuxbrew/wezterm

tap xpipe-io/tap
