
# tap repositories and their packages

tap homebrew/core
brew aqua
brew ast-grep
brew aws-nuke
brew aws-shell
brew aws-vault
brew awscli
brew awscli-local
brew awslogs
brew awsume
brew awsweeper
brew bat
brew bat-extras
brew block-goose-cli
brew bore-cli
brew bottom
brew broot
brew btop
brew catimg
brew cheat
brew checkov
brew chezmoi
brew clipboard
brew ctop
brew d2
brew diff-so-fancy
brew difftastic
brew direnv
brew diskonaut
brew dive
brew dnstop
brew dua-cli
brew dust
brew eza
brew fabric-ai
brew fastgron
brew fd
brew forgit
brew fzf
brew gcc
brew gcli
brew gh
brew git-delta
brew git-interactive-rebase-tool
brew glab
brew glow
brew go
brew gping
brew gron
brew grype
brew hcledit
brew hstr
brew htop
brew hub
brew iftop
brew imagemagick
brew infracost
brew inxi
brew ipcalc
brew k9s
brew kind
brew krew
brew kubecolor
brew kubectx
brew kubernetes-cli
brew lazydocker
brew lazygit
brew lnav
brew localstack
brew lsd
brew luarocks
brew mermaid-cli
brew minikube
brew mise
brew mods
brew mongosh
brew most
brew nb
brew neofetch
brew neovim
brew nerdctl
brew nethogs
brew nnn
brew opencode
brew peco
brew pipx
brew plantuml
brew poppler
brew pre-commit
brew ranger
brew resvg
brew rich-cli
brew ripgrep
brew ripgrep-all
brew rustup
brew starship
brew stern
brew tailspin
brew tectonic
brew tenv
brew terraform-docs
brew terraform-graph-beautifier
brew terraform-local
brew terraform-provider-libvirt
brew terraform_landscape
brew terrahelp
brew terrascan
brew tfk8s
brew tflint
brew tfmigrate
brew tfschema
brew tfsec
brew tfupdate
brew the_silver_searcher
brew tlrc
brew tpm
brew tree-sitter-cli
brew trippy
brew trivy
brew trzsz-go
brew ttyd
brew universal-ctags
brew vale
brew vifm
brew vivid
brew xplr
brew yazi
brew zoxide
brew zsh-completions

tap aquaproj/aqua

tap aurc/loggo
brew aurc/loggo/loggo

tap charmbracelet/tap
brew charmbracelet/tap/crush
brew charmbracelet/tap/soft-serve

tap fluxcd/tap
brew fluxcd/tap/flux

tap future-architect/tap
brew future-architect/tap/tftarget

tap gromgit/brewtils
brew gromgit/brewtils/taproom

tap gu1llaum-3/sshm
brew gu1llaum-3/sshm/sshm

tap hashicorp/tap

tap jckuester/tap
brew jckuester/tap/awsls

tap jmattaa/laser
brew jmattaa/laser/laser

tap one2nc/cloudlens
brew one2nc/cloudlens/cloudlens

tap panter-dsd/tap

tap philocalyst/tap
brew philocalyst/tap/caligula

tap rcmdnk/file
brew rcmdnk/file/brew-file

tap stefanlogue/tools

tap timothyye/tap
brew timothyye/tap/skm

tap unhappychoice/tap
brew unhappychoice/tap/gittype

tap valkyrie00/bbrew
brew valkyrie00/bbrew/bbrew

tap weaveworks/tap
brew weaveworks/tap/gitops

tap wez/wezterm-linuxbrew
brew wez/wezterm-linuxbrew/wezterm

tap xpipe-io/tap
