# ~/.zshrc file for zsh interactive shells.
# see /usr/share/doc/zsh/examples/zshrc for examples

echo "Loading interactive shell config..."

## Source common shell configuration
if [ -f "$HOME/.config/shell/shellrc" ]; then
    source "$HOME/.config/shell/shellrc"
fi

# vim: set syntax=zsh :
