colors.draw_bold_text_with_bright_colors = true

colors.transparent_background_colors = true

colors.indexed_colors = [
  { index = 255, color = "#8BE9FD"},
]

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"
#dim_foreground = "#e1e1e2"
#bright_foreground = "#ffffff"

[colors.normal]
black = "#21222c"
blue = "#bd93f9"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#f8f8f2"
yellow = "#f1fa8c"

[colors.bright]
black = "#6272a4"
blue = "#d6acff"
cyan = "#a4ffff"
green = "#69ff94"
magenta = "#ff92df"
red = "#ff6e6e"
white = "#ffffff"
yellow = "#ffffa5"

[colors.dim]
black = "#14151b"
blue = "#4d5b86"
cyan = "#59dffc"
green = "#1ef956"
magenta = "#ff46b0"
red = "#ff2222"
white = "#e6e6d1"
yellow = "#ebf85b"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.hints.start]
background = "#f1fa8c"
foreground = "#282a36"

[colors.hints.end]
background = "#282a36"
foreground = "#f1fa8c"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.selection]
background = "#576E6F"
text = "#F9F8FF"

[colors.footer_bar]
background = "#282a36"
foreground = "#f8f8f2"

[colors.search.matches]
background = "#50fa7b"
foreground = "#44475a"

[colors.search.focused_match]
background = "#ffb86c"
foreground = "#44475a"

