[font]
size = 12

[font.normal]
family = "VictorMono NF"
style = "Regular"

[font.bold]
family = "VictorMono NF"
style = "Bold"

[font.italic]
family = "VictorMono NF"
style = "Oblique"

[font.bold_italic]
family = "VictorMono NF"
style = "Bold Oblique"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

