[keyboard]
bindings = [
  { action = "IncreaseFontSize", key = "+", mods = "Control|Shift" },
  { action = "DecreaseFontSize", key = "-", mods = "Control|Shift" },
  { action = "ResetFontSize", key = "=", mods = "Control" },
  { action = "ToggleFullScreen", key = "Return", mods="Super" },
  { action = "ToggleFullScreen", key = "F11" },
  { action = "CreateNewWindow", key = "N", mods = "Control|Shift" },
  { action = "SearchBackward", key = "B", mods = "Control|Shift" },
  { action = "SearchForward", key = "F", mods = "Control|Shift" },
  { action = "Paste", key = "V", mods = "Control|Shift", mode = "~Vi" },
  { action = "Copy", key = "C", mods = "Control|Shift" },
  { action = "ScrollHalfPageUp", key = "PageUp", mods = "Control|Shift" },
  { action = "ScrollHalfPageDown", key = "PageDown", mods = "Control|Shift" },
  { action = "ScrollLineUp", key = "Up", mods = "Control|Shift" },
  { action = "ScrollLineDown", key = "Down", mods = "Control|Shift" },
  # Tabs are macOS exclusive features
  { action = "CreateNewTab", key = "T", mods = "Control|Shift" },
  { action = "SelectNextTab", key = "Tab", mods = "Control" },
  { action = "SelectNextTab", key = "Right", mods = "Control|Shift" },
  { action = "SelectPreviousTab", key = "Tab", mods = "Control|Shift" },
  { action = "SelectPreviousTab", key = "Left", mods = "Control|Shift" },
  #{ action = "SelectFirstTab", key = "Home", mods = "Control|Shift" },
  #{ action = "SelectLastTab", key = "End", mods = "Control|Shift" },
  { action = "SelectTab1", key = "1", mods = "Control|Shift" },
  { action = "SelectTab2", key = "2", mods = "Control|Shift" },
  { action = "SelectTab3", key = "3", mods = "Control|Shift" },
  { action = "SelectTab4", key = "4", mods = "Control|Shift" },
  { action = "SelectTab5", key = "5", mods = "Control|Shift" },
  { action = "SelectTab6", key = "6", mods = "Control|Shift" },
  { action = "SelectTab7", key = "7", mods = "Control|Shift" },
  { action = "SelectTab8", key = "8", mods = "Control|Shift" },
  { action = "SelectTab9", key = "9", mods = "Control|Shift" },
]

