[general]
live_config_reload = true
import = ["~/.config/alacritty/catppucin-frappe.toml", "~/.config/alacritty/font.toml", "~/.config/alacritty/keys.toml"]

[env]
#TERM = "xterm-256color"
TERM = "alacritty-direct"

[window]
decorations = "none"
dynamic_title = true
dynamic_padding = false
opacity = 0.85
blur = true
startup_mode = "Windowed"
option_as_alt = "Both"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[scrolling]
history = 50000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>	'''

[cursor.style]
blinking = "On"
shape = "Underline"

[mouse]
hide_when_typing = true

[hints]

