# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

## Source common shell configuration
if [ -f "$XDG_CONFIG_HOME/shell/shellrc" ]; then
    source "$XDG_CONFIG_HOME/shell/shellrc"
fi


# vim: set syntax=bash :
